# Variables 

In [1]:
x = 3

3

In [2]:
y = 4
x + y

7

In [38]:
const pi = 3.14

3.14

# Data types

In [2]:
typeof(10)

Int64

In [3]:
typeof(3.14)

Float64

In [4]:
typeof("Hello,world!") #Sequence of characters

String

In [5]:
typeof(true)

Bool

In [8]:
typeof((1,"hello",3.14)) #Collection of values of different or same types

Tuple{Int64, String, Float64}

In [9]:
typeof([1,2,3,4]) #Collection of values of the same type

Vector{Int64} (alias for Array{Int64, 1})

In [12]:
typeof(Set([1,2,3,4,1]))
Set([1,2,3,4,1]) #Collection of unique values

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [13]:
typeof(1+2im)

Complex{Int64}

# Operators

## Arithmetic operators

In [14]:
1+2 #addition

3

In [15]:
1-2 #subtraction

-1

In [16]:
1*2 #multiplication

2

In [17]:
1/2 #division

0.5

In [18]:
1^2 #exponential

1

In [19]:
1%2 #modulo

1

In [20]:
1\2 #integer division

2.0

## comparison operators

In [23]:
5 == 5.0 #equality

true

In [24]:
4 != 5 #inequality

true

In [25]:
4 < 5 #less than

true

In [26]:
5 > 5 #greater than

false

In [27]:
5 <= 5 #less than or equal

true

In [28]:
4 >= 5 #greater than or equal

false

## Logical operators

In [30]:
a = true
b = false
a && b #and

false

In [31]:
a || b #or

true

In [32]:
!b #not

true

## Assignment operators

In [33]:
x = 5
x

5

In [34]:
x+=3

8

In [35]:
x-=3

5

In [36]:
x*=3

15

In [37]:
x/=3

5.0

# Bitwise operators

 # Conditional statements

Here, condition is any expression that returns a boolean value, either true or false. The if statement checks the value of the condition, and if it's true, the code inside the block following the if keyword will be executed. If it's false, the elseif and else blocks (if they exist) will be evaluated. If multiple conditions are used, only the first one that is true will be executed

In [42]:
x = 5
if x > 0
    println("x is positive")
elseif x < 0
    print("x is negative")
else
    println("x is zero")
end

x is positive


# Loops

In [55]:
for i in 1:5
    println(i)
end

1
2
3
4
5


In [56]:
sum = 0
for i in 1:100
    sum = sum + i
end
println(sum)


5050


In [57]:
arr = [1, 2, 3, 4, 5]
for i in arr
    println(i)
end


1
2
3
4
5


In [58]:
arr = ["apple", "banana", "cherry"]
for (i, fruit) in enumerate(arr)
    println("$i: $fruit")
end


1: apple
2: banana
3: cherry


In [60]:
for i in 1:100
    if i == 5
        break
    end
    println(i)
end


1
2
3
4


In [44]:
i = 1
while i <= 5
    println(i)
    i = i + 1
end


1
2
3
4
5


In [61]:
count = 0
while count < 5
    count += 1
    println("The count is: ", count)
end


The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5


In [62]:
sum = 0
count = 1
while count <= 10
    sum += count
    count += 1
end
println("The sum of the numbers from 1 to 10 is: ", sum)


The sum of the numbers from 1 to 10 is: 55


# Functions

In [63]:
sqrt(16)

4.0

In [64]:
length("Julia")

5

In [45]:
function add(a,b)
    c = a+b
    return c
end

add (generic function with 1 method)

In [46]:
z = add(1,3)

4

In [47]:
function absolute_value(x)
    if x >= 0
        return x
    else
        return -x
    end
end


absolute_value (generic function with 1 method)

In [48]:
absolute_value(-5)

5

In [49]:
function factorial(n)
    result = 1
    for i in 1:n
        result *= i
    end
    return result
end


factorial (generic function with 1 method)

In [50]:
factorial(5)

120

In [51]:
function maximum(a, b)
    if a > b
        return a
    else
        return b
    end
end


maximum (generic function with 1 method)

In [52]:
maximum(3,5)

5

In [53]:
function minimum(a, b)
    if a < b
        return a
    else
        return b
    end
end


minimum (generic function with 1 method)

In [54]:
minimum(1,2)

1

## Anonymous functions
lamda function

In [67]:
add2 = (x,y) -> x+y
add2(3,4)

7

# Arrays and matrices

In [1]:
a = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [10]:
b = [1.0,2.0,3.0,3.0,5.0]

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 3.0
 5.0

In [11]:
a[3]

3

In [12]:
a[3:5]

3-element Vector{Int64}:
 3
 4
 5

In [13]:
a[1] #indexing starts from 1

1

In [14]:
a+b

5-element Vector{Float64}:
  2.0
  4.0
  6.0
  7.0
 10.0

In [16]:
a .+ b

5-element Vector{Float64}:
  2.0
  4.0
  6.0
  7.0
 10.0

In [17]:
a.*b #element wise multiplication

5-element Vector{Float64}:
  1.0
  4.0
  9.0
 12.0
 25.0

In [21]:
A= [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [22]:
B = [5 6; 7 8]

2×2 Matrix{Int64}:
 5  6
 7  8

In [23]:
A+B

2×2 Matrix{Int64}:
  6   8
 10  12

In [25]:
transpose(A)

2×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [26]:
inv(A)

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [29]:
using LinearAlgebra
det(A)

-2.0

In [30]:
dot(A,B)

70

In [31]:
A * B

2×2 Matrix{Int64}:
 19  22
 43  50

In [36]:
A = [1 2 3; 4 5 6; 7 8 9]
A[1,:] # access all of first row

3-element Vector{Int64}:
 1
 2
 3

In [39]:
A[:,2] # access all of second column

3-element Vector{Int64}:
 2
 5
 8

In [40]:
A[1,2]

2

In [41]:
A[2:3,1:2]

2×2 Matrix{Int64}:
 4  5
 7  8

# Broadcasting and vectorization

In [46]:
a = [1,2,3,4]
b = 2

2

In [49]:
#a + b  wont work
a .+b # will broadcast b into [2,2,2,2]

4-element Vector{Int64}:
 3
 4
 5
 6

In [50]:
a = [1 2; 3 4]
b = [2,3]

2-element Vector{Int64}:
 2
 3

In [52]:
# a + b wont work
a .+ b # will broadcast b

2×2 Matrix{Int64}:
 3  4
 6  7

# Advanced programming concepts in Julia

# Types and type hierarchy

In [53]:
Integer <: Real <: Number

true

In [54]:
Number <: Real

false

In [55]:
Number >: Real

true

# Metaprogramming and macros

# Parallel computing and multi-threading

# Interfacing with other languages (e.g. C, Python)

In [58]:
using PyCall
math = pyimport("math")
result = math.sqrt(16)

println("The square root of 16 is $(result)")


The square root of 16 is 4.0


In [61]:
using PyCall
np = pyimport("numpy")
array = np.array([[1, 2], [3, 4]])
println("The NumPy array is: \n $(array)")


The NumPy array is: 
 [1 2; 3 4]


In [62]:
using RCall
R"""
x <- c(1,2,3)
mean(x)
"""


┌ Warning: RCall.jl: During startup - Warning message:
│ package 'stats' in options("defaultPackages") was not found 
└ @ RCall C:\Users\Ahmed\.julia\packages\RCall\Wyd74\src\io.jl:172


RObject{RealSxp}
[1] 2


# Working with packages and libraries

# Data analysis and visualization

DataFrames
StatsBase
GLM
Plots

# DataFrames

In [63]:
using DataFrames

In [64]:
DataFrame()

0×0 DataFrame

In [65]:
DataFrame(A=1:3, B=5:7, fixed=1)

3×3 DataFrame
 Row │ A      B      fixed 
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      5      1
   2 │     2      6      1
   3 │     3      7      1

# Reading and writing data

# Cleaning and preprocessing data

# Exploratory data analysis

# Data visualization with Plots.jl and other libraries

# Scientific computing

# Numerical methods and linear algebra

# Optimization and root finding

### Unconstrained optimization


In [69]:
using Optim
f(x) = (x - 2)^3
result = optimize(f, -10, 10)
println("The minimum of the function is: ", result.minimum)
println("The optimal x value is: ", result.minimizer)


The minimum of the function is: -1727.9999044278736
The optimal x value is: -9.999999778768222


### Constrained optimization

In [91]:
using JuMP
using GLPK

m = Model(GLPK.Optimizer)

# Define variables
@variable(m, x >= 0)
@variable(m, y >= 0)

# Define constraints
@constraint(m, x + 2y <= 10)
@constraint(m, x - y <= 5)

# Define objective function
@objective(m, Max, 3x + 4y)

# Solve the optimization problem
optimize!(m)

# Display the optimal solution
println("Optimal Solution: x = ", value(x), " y = $(value(y))")

Optimal Solution: x = 6.666666666666667 y = 1.6666666666666665


### Root finding

### Nonlinear equations

### Interpolation

### Differentiation

### Numerical linear algebra

### ODE solvers

### Optimization algorithms

# Differential equations

# Interpolation and extrapolation

# Machine learning and artificial intelligence

# Overview of machine learning and artificial intelligence

# Supervised learning and regression

# Unsupervised learning and clustering

# Deep learning with Flux.jl

# Applications and case studies

# Case studies in various domains (e.g. finance, biology, engineering)

# Best practices for software development and testing

# Profiling and performance optimization